from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

import f3_spikes


class F3SpikeSemanticsTests(unittest.TestCase):
    def test_engine_reference_and_alternative_match(self) -> None:
        events = f3_spikes._generate_ledger_events(1_000, 1234)
        reference = f3_spikes.ledger_reference_decimal(events, 999)
        alternative = f3_spikes.ledger_alternative_integer(events, 999)
        self.assertEqual(reference, alternative)

    def test_late_correction_is_not_visible_before_known_at(self) -> None:
        events = f3_spikes._generate_ledger_events(300, 99)
        historical = f3_spikes.ledger_reference_decimal(events, 299)
        corrected = f3_spikes.ledger_reference_decimal(events, 400)
        self.assertNotEqual(historical, corrected)

    def test_contract_supports_n_and_n_minus_1_only(self) -> None:
        state = {"seen": {}, "side_effect_count": 0}
        self.assertTrue(
            f3_spikes._local_contract_call(
                {"action": "ping", "contract_revision": 2}, state
            )["ok"]
        )
        self.assertTrue(
            f3_spikes._local_contract_call(
                {"action": "ping", "contract_revision": 1, "extra": "safe"}, state
            )["ok"]
        )
        self.assertEqual(
            f3_spikes._local_contract_call(
                {"action": "ping", "contract_revision": 0}, state
            )["error"],
            "UNSUPPORTED_CONTRACT_VERSION",
        )

    def test_replayed_submit_does_not_repeat_side_effect(self) -> None:
        state = {"seen": {}, "side_effect_count": 0}
        request = {"action": "submit", "contract_revision": 2, "idempotency_key": "same"}
        first = f3_spikes._local_contract_call(request, state)
        second = f3_spikes._local_contract_call(request, state)
        self.assertFalse(first["replayed"])
        self.assertTrue(second["replayed"])
        self.assertEqual(state["side_effect_count"], 1)

    def test_sqlite_contention_proxy_preserves_exact_counts(self) -> None:
        with tempfile.TemporaryDirectory() as temp_name:
            result = f3_spikes._sqlite_contention_once(Path(temp_name), 0)
        self.assertTrue(result["correctness"])
        self.assertTrue(result["backup_restore_equal"])

    def test_breaking_migration_requires_data_state_mapping(self) -> None:
        result = f3_spikes.run_e_change_01()
        oracle = result["semantic_oracle"]
        self.assertTrue(oracle["ownerless_breaking_migration_blocked"])
        self.assertTrue(oracle["missing_data_state_mapping_blocked"])
        self.assertTrue(oracle["complete_breaking_migration_allowed_by_fixture"])
        self.assertIn("data_state_mapping", result["migration_fixture"]["required_fields"])


class F3CandidateTests(unittest.TestCase):
    def test_generated_candidate_keeps_path_unselected(self) -> None:
        if not f3_spikes.CANDIDATE_PATH.exists():
            self.skipTest("candidate is generated by f3_spikes.py")
        candidate = json.loads(f3_spikes.CANDIDATE_PATH.read_text(encoding="utf-8"))
        self.assertIsNone(candidate["path_decision"]["selected"])
        self.assertFalse(candidate["path_decision"]["ranked"])
        self.assertIn(
            "E-PATH-01",
            {item["experiment"] for item in candidate["decisive_experiments_unrun"]},
        )
        self.assertIn(
            "Actual PostgreSQL transactional candidate under equivalent contention/backup/restore workload",
            {item["missing"] for item in candidate["decisive_experiments_unrun"]},
        )
        self.assertEqual(
            candidate["conclusions"]["E-PERF-02"]["disposition"],
            "REJECT_CURRENT_SHARED_THREADS_AND_SPLIT_PROCESS_FIXTURES_FOR_W1; DEFER_COMPUTE_BOUNDARY_DECISION",
        )
        missing = candidate["conclusions"]["E-PERF-02"]["coverage"]["decisive_missing_or_failed"]
        self.assertIn("C-JOB-03", missing)
        self.assertIn("C-PERF-01", missing)
        self.assertIn("C-PERF-02", missing)
        self.assertIn("C-PERF-05", missing)
        raw = json.loads(f3_spikes.RAW_PATH.read_text(encoding="utf-8"))
        reviewed = raw["experiments"]["E-PERF-02"]["reviewed_baseline_evidence"]
        self.assertTrue(reviewed["both_candidates_fail_frozen_w1"])
        self.assertGreater(reviewed["candidate_control_p95_over_w0"]["shared-process-threads"], 2.0)
        self.assertGreater(reviewed["candidate_control_p95_over_w0"]["split-process-workers"], 2.0)

    def test_generated_recovery_evidence_compares_frozen_30s_target(self) -> None:
        if not f3_spikes.RAW_PATH.exists():
            self.skipTest("raw artifact is generated by f3_spikes.py")
        raw = json.loads(f3_spikes.RAW_PATH.read_text(encoding="utf-8"))
        timing = raw["experiments"]["E-PERF-02"]["recovery"]["owner_loss_timing"]
        self.assertEqual(timing["fixture_target_seconds"], 30.0)
        self.assertTrue(timing["logical_target_met"])
        self.assertIn("not evidence for arbitrary OS/process kill", timing["limit"])


if __name__ == "__main__":
    unittest.main()
